export default {
  palm_logo: require('./palm_logo.png'),
  loading: require('./loading.gif'),
  blank_profile: require('./blank_profile.png'),
  eth_logo: require('./eth_logo.png'),
  klay_logo: require('./klay_logo.png'),
  matic_logo: require('./matic_logo.png'),
  profile_temp: require('./profile_temp.png'),
  arrow_right: require('./arrow_right.png'),
  list: require('./list.png'),
  NFT: require('./NFT.png'),
  NFT_black: require('./NFT_black.png'),
  image_blue: require('./image_blue.png'),
  select_image: require('./select_image.png'),
  create_channel: require('./create_channel.png'),
  import: require('./import.png'),
  plus: require('./plus.png'),
  pin_delete: require('./pin_delete.png'),
  no_img: require('./no_img.png'),
  spinner: require('./spinner.json'),
  splash: require('./splash.json'),
  repeat: require('./repeat.png'),
  crown: require('./crown.png'),
  checkbox_on: require('./checkbox_on.png'),
  checkbox_off: require('./checkbox_off.png'),
  samples: [
    require('./temp/thumbs1.png'),
    require('./temp/thumbs2.png'),
    require('./temp/thumbs3.png'),
    require('./temp/thumbs4.png'),
    require('./temp/thumbs5.png'),
    require('./temp/thumbs6.png'),
    require('./temp/thumbs7.png'),
    require('./temp/thumbs8.png'),
    require('./temp/thumbs9.png'),
  ],
}
