export enum QueryKeyEnum {
  ROUTE_PARAMS = 'ROUTE_PARAMS',

  ETH_USD_PRICE = 'ETH_USD_PRICE',

  TX_INFO = 'TX_INFO',

  KLAY_BALANCE = 'KLAY_BALANCE',

  NFT_TOKENS_OF_OWNER = 'NFT_TOKENS_OF_OWNER',
  NFT_TOKEN_BALANCE_OF = 'NFT_TOKEN_BALANCE_OF',
  NFT_APPROVED = 'NFT_APPROVED',
  NFT_TOKEN_URI = 'NFT_TOKEN_URI',
  ESCROW_CHANNEL_NFTS = 'ESCROW_CHANNEL_NFTS',

  MORALIS_NFT_IMAGE = 'MORALIS_NFT_IMAGE',

  ZX_SWAP_SDK_V4 = 'ZX_SWAP_SDK_V4',
  ZX_ORDERS = 'ZX_ORDERS',
  ZX_ORDER = 'ZX_ORDER',
}
