export enum QueryKeyEnum {
  ROUTE_PARAMS = 'ROUTE_PARAMS',

  TX_INFO = 'TX_INFO',

  KLAY_BALANCE = 'KLAY_BALANCE',

  NFT_TOKENS_OF_OWNER = 'NFT_TOKENS_OF_OWNER',
  NFT_APPROVED = 'NFT_APPROVED',
  NFT_TOKEN_URI = 'NFT_TOKEN_URI',
  ESCROW_CHANNEL_NFTS = 'ESCROW_CHANNEL_NFTS',

  MORALIS_NFT_IMAGE = 'MORALIS_NFT_IMAGE',

  VESTINGS = 'VESTINGS',
  VESTINGS_BY_USER = 'VESTINGS_BY_USER',
  IS_ADMIN = 'IS_ADMIN',

  VESTING_INFO = 'VESTING_INFO',
  VESTING_EXCESS_AMOUNT = 'VESTING_EXCESS_AMOUNT',
}
