export enum QueryKeyEnum {
  ROUTE_PARAMS = 'ROUTE_PARAMS',

  ETH_USD_PRICE = 'ETH_USD_PRICE',
  KLAY_USD_PRICE = 'KLAY_USD_PRICE',
  MATIC_USD_PRICE = 'MATIC_USD_PRICE',

  TX_INFO = 'TX_INFO',

  NATIVE_TOKEN_BALANCE = 'NATIVE_TOKEN_BALANCE',

  NFT_TOKEN_NAME = 'NFT_TOKEN_NAME',
  NFT_TOKENS_OF_OWNER = 'NFT_TOKENS_OF_OWNER',
  NFT_TOKEN_BALANCE_OF = 'NFT_TOKEN_BALANCE_OF',
  NFT_APPROVED = 'NFT_APPROVED',
  NFT_TOKEN_URI = 'NFT_TOKEN_URI',
  ESCROW_CHANNEL_NFTS = 'ESCROW_CHANNEL_NFTS',

  MORALIS_NFT_IMAGE = 'MORALIS_NFT_IMAGE',

  ZX_SWAP_SDK_V4 = 'ZX_SWAP_SDK_V4',
  ZX_ORDERS = 'ZX_ORDERS',
  ZX_ORDER = 'ZX_ORDER',

  WEB3_BINDINGS = 'WEB3_BINDINGS',

  LENS_PROFILES = 'LENS_PROFILES',
  LENS_DEFAULT_PROFILE = 'LENS_DEFAULT_PROFILE',

  CHANNEL_GATING_CHECK = 'CHANNEL_GATING_CHECK',
}
