platform :ios do

  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match
  end

  desc 'Fetch certificates. Build the iOS application.'
  lane :build do
    certificates
    gym
  end

  desc 'Fetch certificates, build and upload to App Center.'
  lane :beta do
    build
    appcenter_upload(
      api_token: ENV["APPCENTER_API_TOKEN"],
      owner_name: ENV["APPCENTER_OWNER_NAME"],
      app_name: ENV["APPCENTER_IOS_APP_NAME"],
      ipa: ENV["APPCENTER_DISTRIBUTE_IPA"],
      destinations: "*",
      notify_testers: true
    )
  end

end

# Generated .apk will be at android/app/build/outputs/apk/release/app-release.apk
platform :android do

  desc 'Build the Android application.'
  lane :build do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'assemble', build_type: 'release', project_dir: 'android/')
  end

  desc 'Build and upload to App Center.'
  lane :beta do
    build
    appcenter_upload(
      api_token: ENV["APPCENTER_API_TOKEN"],
      owner_name: ENV["APPCENTER_OWNER_NAME"],
      app_name: ENV["APPCENTER_ANDROID_APP_NAME"],
      apk: ENV["APPCENTER_DISTRIBUTE_APK"],
      destinations: "*",
      notify_testers: true
    )
  end

end
