export default {
  palm_logo: require('./palm_logo.png'),
  loading: require('./loading.gif'),
  splash: require('./splash.png'),
  blank_profile: require('./blank_profile.png'),
  eth_logo: require('./eth_logo.png'),
  klay_logo: require('./klay_logo.png'),
  matic_logo: require('./matic_logo.png'),
  profile_temp: require('./profile_temp.png'),
  arrow_right: require('./arrow_right.png'),
  list: require('./list.png'),
  NFT: require('./NFT.png'),
  NFT_black: require('./NFT_black.png'),
  image_blue: require('./image_blue.png'),
  select_image: require('./select_image.png'),
  create_channel: require('./create_channel.png'),
  import: require('./import.png'),
  plus: require('./plus.png'),
}
